/**
 * GET /api/stock/[symbol]/analysis
 *
 * Snapshot-first for stored analyses, BUT:
 *  - ?refresh=1 bypasses cache/store and regenerates via Gemini
 *  - If stored analysis was generated by the fallback (no Gemini),
 *    and GEMINI_API_KEY is now set, automatically regenerate.
 *
 * Response includes debug metadata:
 *  - geminiKeyPresent, model, source, geminiError
 */

import { NextResponse } from "next/server";
import { computeIndicators } from "@/lib/calculations";
import { generateStockAnalysis, getGeminiStatus } from "@/lib/gemini";
import { cache, TTL } from "@/lib/cache";
import { loadAnalysis, saveAnalysis, loadQuote, loadHistory, loadNews } from "@/lib/store";
import type { TechnicalIndicators } from "@/lib/types";

function fallbackIndicators(price: number): TechnicalIndicators {
  return {
    rsi: 50, relativeVolume: 1, trendRegime: "Sideways",
    ma20: price, ma50: price, ma200: price,
    priceVsMa50Pct: 0, priceVsMa200Pct: 0,
    setupScore: 0, setupLabel: "Neutral",
    high52w: price, low52w: price, distFrom52wHighPct: 0,
  };
}

/**
 * Detect whether a stored analysis was generated by the rule-based fallback
 * (i.e. Gemini was NOT used). Heuristic: the fallback always sets confidence
 * to "Low" and includes a distinctive risks string.
 */
function isFallbackAnalysis(analysis: { risks?: string[]; confidence?: string }): boolean {
  if (analysis.confidence === "Low") {
    const risksText = (analysis.risks ?? []).join(" ").toLowerCase();
    if (
      risksText.includes("rule-based fallback") ||
      risksText.includes("no gemini api key") ||
      risksText.includes("ai analysis unavailable") ||
      risksText.includes("add gemini_api_key")
    ) {
      return true;
    }
  }
  return false;
}

export async function GET(
  req: Request,
  { params }: { params: { symbol: string } }
) {
  const symbol = params.symbol.toUpperCase();
  const { searchParams } = new URL(req.url);
  const forceRefresh = searchParams.get("refresh") === "1";

  const geminiStatus = getGeminiStatus();
  const cacheKey = `analysis:${symbol}`;

  // ── Skip cache/store on ?refresh=1 ─────────────────────────────────────────
  if (!forceRefresh) {
    // 1. In-memory cache
    const cached = cache.get(cacheKey);
    if (cached) {
      return NextResponse.json({
        data: cached, error: null, source: "cache",
        _debug: { ...geminiStatus, geminiCalled: false },
      });
    }

    // 2. SQLite store — serve if present, UNLESS it's a stale fallback and
    //    we now have a Gemini key (meaning we should regenerate with AI).
    const stored = loadAnalysis(symbol);
    if (stored) {
      const shouldRegenerate = geminiStatus.hasKey && isFallbackAnalysis(stored.data);
      if (!shouldRegenerate) {
        cache.set(cacheKey, stored.data, TTL.ANALYSIS);
        return NextResponse.json({
          data: stored.data, error: null,
          cachedAt: stored.updatedAt, stale: stored.stale, source: "store",
          _debug: { ...geminiStatus, geminiCalled: false, wasFallback: isFallbackAnalysis(stored.data) },
        });
      }
      // Fall through to regeneration
      console.log(`[analysis/${symbol}] Stored analysis is fallback and Gemini key is now present — regenerating`);
    }
  } else {
    // Clear in-memory cache so the fresh result replaces it
    cache.delete(cacheKey);
  }

  // ── Generate fresh analysis ────────────────────────────────────────────────
  const sq = loadQuote(symbol);
  if (!sq) {
    return NextResponse.json({
      data: null,
      error: `No data for ${symbol} — run Full Refresh first.`,
      _debug: { ...geminiStatus, geminiCalled: false },
    }, { status: 404 });
  }

  try {
    const quote = sq.data;
    const sh = loadHistory(symbol);
    const sn = loadNews(symbol);

    const bars = sh?.data ?? [];
    const newsHeadlines = sn?.data.map((n) => n.title) ?? [];

    const indicators = bars.length >= 15
      ? computeIndicators(bars, quote.volume || undefined)
      : fallbackIndicators(quote.price);

    const result = await generateStockAnalysis({
      symbol: quote.symbol,
      shortName: quote.shortName,
      price: quote.price,
      changePercent: quote.changePercent,
      indicators,
      newsHeadlines,
    });

    cache.set(cacheKey, result.analysis, TTL.ANALYSIS);
    saveAnalysis(symbol, result.analysis);

    return NextResponse.json({
      data: result.analysis,
      error: result.geminiError ? `Gemini failed: ${result.geminiError} (showing fallback)` : null,
      source: result.source === "gemini" ? "generated" : "fallback",
      _debug: {
        ...geminiStatus,
        geminiCalled: true,
        geminiSource: result.source,
        geminiError: result.geminiError,
      },
    });
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error(`[analysis/${symbol}]`, errMsg);

    // Return stale store data if available
    const stored = loadAnalysis(symbol);
    if (stored) {
      return NextResponse.json({
        data: stored.data,
        error: `Generation failed: ${errMsg} (showing cached)`,
        cachedAt: stored.updatedAt, stale: true, source: "store-stale",
        _debug: { ...geminiStatus, geminiCalled: true, geminiError: errMsg },
      });
    }

    return NextResponse.json({
      data: null,
      error: `Failed to generate analysis: ${errMsg}`,
      _debug: { ...geminiStatus, geminiCalled: true, geminiError: errMsg },
    }, { status: 500 });
  }
}
