/**
 * GET /api/stock/[symbol]/analysis
 *
 * Snapshot-first for stored analyses, BUT:
 *  - ?refresh=1 bypasses cache/store and regenerates via Gemini
 *  - If stored analysis was generated by the fallback (no Gemini),
 *    and GEMINI_API_KEY is now set, automatically regenerate.
 *
 * Response includes debug metadata:
 *  - geminiKeyPresent, model, source, geminiError
 */

import { NextResponse } from "next/server";
import { normalizeLocale } from "@/lib/app-settings";
import { computeIndicators } from "@/lib/calculations";
import { getAssetNoun, normalizeQuote } from "@/lib/assets";
import { generateStockAnalysis, getAiStatus } from "@/lib/gemini";
import { cache, TTL } from "@/lib/cache";
import { loadAnalysis, saveAnalysis, loadQuote, loadHistory, loadNews } from "@/lib/store";
import type { TechnicalIndicators } from "@/lib/types";

function fallbackIndicators(price: number): TechnicalIndicators {
  return {
    rsi: 50, relativeVolume: 1, trendRegime: "Sideways",
    ma20: price, ma50: price, ma200: price,
    priceVsMa50Pct: 0, priceVsMa200Pct: 0,
    setupScore: 0, setupLabel: "Neutral",
    high52w: price, low52w: price, distFrom52wHighPct: 0,
  };
}

/**
 * Detect whether a stored analysis was generated by the rule-based fallback
 * (i.e. Gemini was NOT used). Heuristic: the fallback always sets confidence
 * to "Low" and includes a distinctive risks string.
 */
function isFallbackAnalysis(analysis: {
  risks?: string[];
  confidence?: string;
  source?: string;
  summary?: string;
}): boolean {
  if (analysis.source === "fallback") {
    return true;
  }

  if (analysis.confidence === "Low") {
    const fallbackText = `${(analysis.risks ?? []).join(" ")} ${analysis.summary ?? ""}`.toLowerCase();
    if (
      fallbackText.includes("rule-based fallback") ||
      fallbackText.includes("no gemini api key") ||
      fallbackText.includes("no ai provider") ||
      fallbackText.includes("ai analysis unavailable") ||
      fallbackText.includes("add gemini_api_key") ||
      fallbackText.includes("规则回退") ||
      fallbackText.includes("ai 分析暂不可用") ||
      fallbackText.includes("启用 gemini") ||
      fallbackText.includes("配置可用的 ai 提供方")
    ) {
      return true;
    }
  }
  return false;
}

export async function GET(
  req: Request,
  { params }: { params: { symbol: string } }
) {
  const symbol = params.symbol.toUpperCase();
  const { searchParams } = new URL(req.url);
  const forceRefresh = searchParams.get("refresh") === "1";
  const locale = normalizeLocale(searchParams.get("locale"));
  const selectedProvider = searchParams.get("provider");

  const aiStatus = getAiStatus(selectedProvider);
  const cacheKey = `analysis:${symbol}:${locale}:${aiStatus.provider}`;

  // ── Skip cache/store on ?refresh=1 ─────────────────────────────────────────
  if (!forceRefresh) {
    // 1. In-memory cache
    const cached = cache.get(cacheKey);
    if (cached) {
      return NextResponse.json({
        data: cached, error: null, source: "cache",
        _debug: { ...aiStatus, aiCalled: false, locale },
      });
    }

    // 2. SQLite store — serve if present, UNLESS it's a stale fallback and
    //    we now have a Gemini key (meaning we should regenerate with AI).
    const stored = loadAnalysis(symbol, locale, aiStatus.provider);
    if (stored) {
      const shouldRegenerate = aiStatus.hasKey && isFallbackAnalysis(stored.data);
      if (!shouldRegenerate) {
        cache.set(cacheKey, stored.data, TTL.ANALYSIS);
        return NextResponse.json({
          data: stored.data, error: null,
          cachedAt: stored.updatedAt, stale: stored.stale, source: "store",
          _debug: { ...aiStatus, aiCalled: false, wasFallback: isFallbackAnalysis(stored.data), locale },
        });
      }
      // Fall through to regeneration
      console.log(`[analysis/${symbol}] Stored analysis is fallback for locale=${locale} and provider=${aiStatus.provider} is available — regenerating`);
    }
  } else {
    // Clear in-memory cache so the fresh result replaces it
    cache.delete(cacheKey);
  }

  // ── Generate fresh analysis ────────────────────────────────────────────────
  const sq = loadQuote(symbol);
  if (!sq) {
    return NextResponse.json({
      data: null,
      error: `No data for ${symbol} — run Full Refresh first.`,
      _debug: { ...aiStatus, aiCalled: false, locale },
    }, { status: 404 });
  }

  try {
    const quote = normalizeQuote(sq.data);
    const sh = loadHistory(symbol);
    const sn = loadNews(symbol);

    const bars = sh?.data ?? [];
    const newsHeadlines = sn?.data.map((n) => n.title) ?? [];

    const indicators = bars.length >= 15
      ? computeIndicators(bars, quote.volume || undefined)
      : fallbackIndicators(quote.price);

    const result = await generateStockAnalysis({
      symbol: quote.symbol,
      assetType: quote.assetType ?? "stock",
      shortName: quote.shortName,
      price: quote.price,
      changePercent: quote.changePercent,
      indicators,
      newsHeadlines,
      locale,
      provider: aiStatus.provider,
    });

    cache.set(cacheKey, result.analysis, TTL.ANALYSIS);
    saveAnalysis(symbol, result.analysis, locale, aiStatus.provider);

    return NextResponse.json({
      data: result.analysis,
      error: result.providerError ? `${aiStatus.label} failed: ${result.providerError} (showing fallback)` : null,
      source: result.source !== "fallback" ? "generated" : "fallback",
      _debug: {
        ...aiStatus,
        aiCalled: true,
        aiSource: result.source,
        aiError: result.providerError,
        locale,
      },
    });
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error(`[analysis/${symbol}]`, errMsg);

    // Return stale store data if available
    const stored = loadAnalysis(symbol, locale, aiStatus.provider);
    if (stored) {
      return NextResponse.json({
        data: stored.data,
        error: `Generation failed: ${errMsg} (showing cached)`,
        cachedAt: stored.updatedAt, stale: true, source: "store-stale",
        _debug: { ...aiStatus, aiCalled: true, aiError: errMsg, locale },
      });
    }

    return NextResponse.json({
      data: null,
      error: `Failed to generate ${getAssetNoun(normalizeQuote(sq.data).assetType ?? "stock")} analysis: ${errMsg}`,
      _debug: { ...aiStatus, aiCalled: true, aiError: errMsg, locale },
    }, { status: 500 });
  }
}
